### ISSUE TITLE
Update mathjax script link

### ISSUE THREAD

**Issue by neonacorns** [saylordotorg/text_intermediate-algebra#1]
In multiple sections:

**broken**: `https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=MML_HTMLorMML`
**replacement**: `https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=MML_HTMLorMML`

I'm hoping that switching out these links will get the textbook equations to display correctly.

**Comment by athuggins** [comment]
Fixed in https://github.com/saylordotorg/text_intermediate-algebra/commit/ef60b1221e79f4abd5fded15e45236ea3acd4560
